-- MySQL Script generated by MySQL Workbench
-- Mon Apr 20 14:15:39 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd` ;
USE `bd` ;

-- -----------------------------------------------------
-- Table `bd`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `usuario` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `telefone` VARCHAR(15) NULL,
  `senha` VARCHAR(255) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `cargo` ENUM('Administrativo', 'Frente de Caixa', 'Repositor', 'Entregador') NOT NULL,
  `is_admin` TINYINT(1) NOT NULL DEFAULT 0,
  `icone` VARCHAR(255) NULL DEFAULT 'default.png',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`permissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`permissoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `tipo` ENUM('visualizar', 'cadastrar', 'editar', 'deletar') NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`permissao_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`permissao_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `permissoes_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `permissoes_id`, `usuarios_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_permissao_usuario_permissoes1_idx` (`permissoes_id` ASC) VISIBLE,
  INDEX `fk_permissao_usuario_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_permissao_usuario_permissoes1`
    FOREIGN KEY (`permissoes_id`)
    REFERENCES `bd`.`permissoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permissao_usuario_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `bd`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`grupo_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`grupo_produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`icms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`icms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `codigo` VARCHAR(3) NOT NULL,
  `tributacao` FLOAT(7,2) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`ipi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`ipi` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `codigo` VARCHAR(3) NOT NULL,
  `tributacao` FLOAT(7,2) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`pis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`pis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `codigo` VARCHAR(3) NOT NULL,
  `tributacao` FLOAT(7,2) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`cofins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`cofins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `codigo` VARCHAR(3) NOT NULL,
  `tributacao` FLOAT(7,2) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `codigo` VARCHAR(13) NOT NULL,
  `preco` FLOAT(7,2) NOT NULL,
  `estoque` FLOAT(7,2) NOT NULL,
  `tipo` ENUM('UN', 'KG', 'CX') NOT NULL,
  `quant_entrada` FLOAT(7,2) NOT NULL,
  `quant_saida` FLOAT(7,2) NOT NULL,
  `grupo_produto_id` INT NOT NULL,
  `icms_id` INT NOT NULL,
  `ipi_id` INT NOT NULL,
  `pis_id` INT NOT NULL,
  `cofins_id` INT NOT NULL,
  `cfop` INT NOT NULL,
  `ncm` INT(8) NULL,
  `cest` INT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_produtos_grupo_produto1_idx` (`grupo_produto_id` ASC) VISIBLE,
  INDEX `fk_produtos_icms1_idx` (`icms_id` ASC) VISIBLE,
  INDEX `fk_produtos_ipi1_idx` (`ipi_id` ASC) VISIBLE,
  INDEX `fk_produtos_pis1_idx` (`pis_id` ASC) VISIBLE,
  INDEX `fk_produtos_cofins1_idx` (`cofins_id` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_grupo_produto1`
    FOREIGN KEY (`grupo_produto_id`)
    REFERENCES `bd`.`grupo_produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_icms1`
    FOREIGN KEY (`icms_id`)
    REFERENCES `bd`.`icms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_ipi1`
    FOREIGN KEY (`ipi_id`)
    REFERENCES `bd`.`ipi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_pis1`
    FOREIGN KEY (`pis_id`)
    REFERENCES `bd`.`pis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_cofins1`
    FOREIGN KEY (`cofins_id`)
    REFERENCES `bd`.`cofins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`vendas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `desconto` INT(100) NOT NULL DEFAULT 0,
  `total` FLOAT(7,2) NOT NULL DEFAULT 0,
  `troco` FLOAT(7,2) NOT NULL DEFAULT 0,
  `usuarios_id` INT NOT NULL,
  `situacao` ENUM('cancelada', 'em andamento', 'em espera', 'concluida') NOT NULL DEFAULT 'em andamento',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_vendas_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_vendas_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `bd`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`venda_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`venda_produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `quantidade` FLOAT(7,2) NOT NULL DEFAULT 1,
  `vendas_id` INT NOT NULL,
  `produtos_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `vendas_id`, `produtos_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_venda_produto_vendas1_idx` (`vendas_id` ASC) VISIBLE,
  INDEX `fk_venda_produto_produtos1_idx` (`produtos_id` ASC) VISIBLE,
  CONSTRAINT `fk_venda_produto_produtos1`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `bd`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_produto_vendas1`
    FOREIGN KEY (`vendas_id`)
    REFERENCES `bd`.`vendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`enderecos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `codigo` INT NULL,
  `cidade` VARCHAR(150) NOT NULL,
  `rua` VARCHAR(255) NOT NULL,
  `bairro` VARCHAR(255) NOT NULL,
  `numero` VARCHAR(10) NOT NULL DEFAULT 'S/N',
  `complemento` VARCHAR(255) NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NULL,
  `documento` VARCHAR(18) NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `ie_rg` VARCHAR(10) NULL DEFAULT 'ISENTO',
  `contribuinte` INT(1) NOT NULL DEFAULT 0,
  `enderecos_id` INT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_clientes_enderecos1_idx` (`enderecos_id` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_enderecos1`
    FOREIGN KEY (`enderecos_id`)
    REFERENCES `bd`.`enderecos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`recuperar_senha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`recuperar_senha` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `usuarios_id` INT NOT NULL,
  `codigo` INT(6) NOT NULL,
  `expires_at` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `usuarios_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_recuperar_senha_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_recuperar_senha_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `bd`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`venda_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`venda_cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `clientes_id` INT NOT NULL,
  `vendas_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `clientes_id`, `vendas_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_venda_fiado_clientes1_idx` (`clientes_id` ASC) VISIBLE,
  INDEX `fk_venda_fiado_vendas1_idx` (`vendas_id` ASC) VISIBLE,
  CONSTRAINT `fk_venda_fiado_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `bd`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_fiado_vendas1`
    FOREIGN KEY (`vendas_id`)
    REFERENCES `bd`.`vendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`pagamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `forma` VARCHAR(100) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`venda_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`venda_pagamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `valor` FLOAT(7,2) NOT NULL,
  `vendas_id` INT NOT NULL,
  `pagamento_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `vendas_id`, `pagamento_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_venda_pagamento_vendas1_idx` (`vendas_id` ASC) VISIBLE,
  INDEX `fk_venda_pagamento_pagamento1_idx` (`pagamento_id` ASC) VISIBLE,
  CONSTRAINT `fk_venda_pagamento_vendas1`
    FOREIGN KEY (`vendas_id`)
    REFERENCES `bd`.`vendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_pagamento_pagamento1`
    FOREIGN KEY (`pagamento_id`)
    REFERENCES `bd`.`pagamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`empresas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `razao_social` VARCHAR(255) NOT NULL,
  `nome_fantasia` VARCHAR(255) NOT NULL,
  `documento` VARCHAR(20) NOT NULL,
  `ie_rg` VARCHAR(10) NOT NULL,
  `num_serie_nfe` INT NOT NULL,
  `enderecos_id` INT NOT NULL,
  `ativo` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_destinatarios_enderecos1_idx` (`enderecos_id` ASC) VISIBLE,
  CONSTRAINT `fk_destinatarios_enderecos1`
    FOREIGN KEY (`enderecos_id`)
    REFERENCES `bd`.`enderecos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`destinatarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`destinatarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `empresas_id` INT NOT NULL,
  `ativo` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `empresas_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_destinatarios_empresas1_idx` (`empresas_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_destinatarios_empresas1`
    FOREIGN KEY (`empresas_id`)
    REFERENCES `bd`.`empresas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`nota_fiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`nota_fiscal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `nat_op` VARCHAR(255) NOT NULL,
  `num_nf` INT NOT NULL,
  `situacao` VARCHAR(100) NOT NULL,
  `vendas_id` INT NOT NULL,
  `destinatarios_id` INT NOT NULL,
  `xml_path` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `vendas_id`, `destinatarios_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_nota_fiscal_vendas1_idx` (`vendas_id` ASC) VISIBLE,
  INDEX `fk_nota_fiscal_destinatarios1_idx` (`destinatarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_nota_fiscal_vendas1`
    FOREIGN KEY (`vendas_id`)
    REFERENCES `bd`.`vendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nota_fiscal_destinatarios1`
    FOREIGN KEY (`destinatarios_id`)
    REFERENCES `bd`.`destinatarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`emitentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`emitentes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `empresas_id` INT NOT NULL,
  `ativo` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `empresas_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_emitentes_empresas1_idx` (`empresas_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_emitentes_empresas1`
    FOREIGN KEY (`empresas_id`)
    REFERENCES `bd`.`empresas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`nota_fiscal_entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`nota_fiscal_entrada` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `chave` VARCHAR(44) NOT NULL,
  `num_nf` INT NOT NULL,
  `nat_op` VARCHAR(255) NOT NULL,
  `gravada` TINYINT NOT NULL DEFAULT 0,
  `data_emissao` DATE NOT NULL,
  `emitentes_id` INT NOT NULL,
  `xml_path` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `emitentes_id`),
  INDEX `fk_nota_fiscal_entrada_emitentes1_idx` (`emitentes_id` ASC) VISIBLE,
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  CONSTRAINT `fk_nota_fiscal_entrada_emitentes1`
    FOREIGN KEY (`emitentes_id`)
    REFERENCES `bd`.`emitentes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
